version: 2.1

parameters:
  build_image:
    type: string
    default: "circleci/python:3.8" 
 
jobs:

  build:
    environment:
      DOCKER_IMAGE: "circleci-deploy"
    docker:  
      - image: << pipeline.parameters.build_image >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS CLI
          command: |
            sudo pip install awscli 
      - run:
          name: Set environment variables
          command: |
            echo 'export TAG=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export DOCKER_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build Docker image 
          command: |
            docker build -t $DOCKER_IMAGE:$TAG .
      - run:
          name: Tag Docker image 
          command: |
            docker tag $DOCKER_IMAGE:$TAG $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
            docker tag $DOCKER_IMAGE:$TAG $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
      - run:
          name: Login to Docker registry
          command: |
            LOGIN_COMMAND=$(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            $LOGIN_COMMAND
      - run:
          name: Push Docker image 
          command: |            
            docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
