version: 2.1

parameters:
  build_image:
    type: string
    default: "circleci/golang:1.13.1-stretch" 

jobs:

  build:
    environment:
      DOCKER_IMAGE: "circleci-deploy"
    docker:  
      - image: << pipeline.parameters.build_image >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image 
          command: |
            echo 'export TAG=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
            echo 'export DOCKER_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com' >> $BASH_ENV
            source $BASH_ENV
            docker build -t $DOCKER_IMAGE:$TAG .
      - run:
          name: Tag Docker image 
          command: |
            docker tag $DOCKER_IMAGE:$TAG $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
            docker tag $DOCKER_IMAGE:$TAG $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
      - run:
          name: Login to Docker registry
          command: |
            sh -c $(aws ecr get-login)
      - run:
          name: Push Docker image 
          command: |            
            docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
