version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t aadamovich/circleci-deploy:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker tag aadamovich/circleci-deploy:$TAG aadamovich/circleci-deploy:latest
          docker push aadamovich/circleci-deploy:$TAG
          docker push aadamovich/circleci-deploy:latest